<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo $pageTitle; ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="<?php echo $pageTitle; ?>">
        <meta name="author" content="J Cobb <j+ticketevolution@teamonetickets.com>">

        <!-- Stylesheets -->
        <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">

        <link rel="shortcut icon" href="/favicon.ico">
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="/"><strong>Ticket Evolution DataLoaders</strong></a></li>
                            <li><a href="https://github.com/TeamOneTickets/ticket-evolution-dataloaders">GitHub <i class="icon-white icon-github"></i></a></li>
                            <li><a href="https://github.com/TeamOneTickets/ticket-evolution-dataloaders/issues" target="_blank">Issues <i class="icon-white icon-share-alt"></i></a></li>
                            <li><a href="http://www.ticketevolution.com/products/api-affiliates-and-partners/" target="_blank">Ticket Evolution <i class="icon-white icon-share-alt"></i></a></li>
                            <li><a href="http://developer.ticketevolution.com/" target="_blank">API Documentation <i class="icon-white icon-share-alt"></i></a></li>
                            <li><a href="http://www.teamonetickets.com/" target="_blank">Team One Tickets <i class="icon-white icon-share-alt"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container main">
